### ISSUE TITLE
How to correctly pass the custom Controls as a prop?

### ISSUE THREAD

**Issue by c-goettert** [ScreamZ/react-native-true-sight#2]
Could you please provide an example on how the Custom-Controls should be passed to the VideoPlayer-Component?

It seems to be working this way:
```javascript
const bottomControls = (props) => <MyControlsComponent {...props} />
return <VideoPlayer bottomControlsBar={bottomControls} source={this.props.source} />
```
But I still get a yellow-box warning me that I use a wrong prop-type:
<img width="317" alt="bildschirmfoto 2018-04-23 um 12 48 00" src="https://user-images.githubusercontent.com/7591624/39122257-9f03dad0-46f4-11e8-9a5a-77241c877263.png">

When I try to pass the Component directly like so:
```javascript
return <VideoPlayer bottomControlsBar={<MyControlsComponent />} source={this.props.source} />
```
RN will give me an error:
<img width="320" alt="bildschirmfoto 2018-04-23 um 12 51 01" src="https://user-images.githubusercontent.com/7591624/39122386-0a1135b6-46f5-11e8-9f9a-31e331f31bcd.png">

Could you please fix the prop-types or provide a working example? Thanks alot!

**Comment by ScreamZ** [comment]
Hello,

Thanks for reporting an issue :).

You should be right with the first statement, can you confirm that you get this working and only have the warning ? I didn't tested with functional components but only with class statement and it didn't triggered the warning if I correctly remember (However, I might be wrong…)

Can you try using this component as control bar and tell me if you still get the warning and if everything is working correctly ? That's the default one, if it triggers, it's only about `prop-type`.

```js
import * as React from "react";
import { View, Text, Slider, StyleSheet } from "react-native";
import * as PropTypes from "prop-types";
export default class BottomControlsBar extends React.PureComponent {
    constructor(props) {
        super(props);
        this.hasMovedSlider = false;
        this.wasPausedBeforeSlide = null;
        this.onSliderTouch = this.onSliderTouch.bind(this);
        this.onSlidingComplete = this.onSlidingComplete.bind(this);
    }
    /**
     * Transform seconds to text giving 08:05 for the example.
     *
     * @param {number} seconds The number of seconds to transform.
     *
     * @returns {string}
     */
    secondsToMS(seconds) {
        const min = Math.floor(seconds / 60);
        const sec = seconds % 60;
        return `${min < 10 ? '0' + min : min}:${sec < 10 ? '0' + sec : sec}`;
    }
    onSliderTouch(val) {
        if (!this.hasMovedSlider) {
            this.hasMovedSlider = true;
            this.wasPausedBeforeSlide = this.props.isPaused; // To know if we need to play after sliding.
            this.props.setPaused();
        }
    }
    onSlidingComplete(val) {
        this.hasMovedSlider = false;
        this.props.setPosition(Math.round(val));
        if (!this.wasPausedBeforeSlide) {
            this.props.setPlaying();
        }
    }
    render() {
        return (<View style={styles.barWrapper}>
        <Text style={styles.currentTime}>
          {this.secondsToMS(this.props.currentTime)}
        </Text>
        <Slider pointerEvents={this.props.navigationAllowed ? undefined : 'none'} style={styles.loadingBar} maximumValue={this.props.totalTime} minimumTrackTintColor={this.props.barColor} thumbTintColor={this.props.joyStickColor} value={this.props.currentTime} onValueChange={this.onSliderTouch} onSlidingComplete={this.onSlidingComplete}/>
        <Text style={styles.totalTime}>
          {this.secondsToMS(this.props.totalTime)}
        </Text>
      </View>);
    }
}
BottomControlsBar.propTypes = {
    // Metadata
    currentTime: PropTypes.number.isRequired,
    totalTime: PropTypes.number.isRequired,
    isPaused: PropTypes.bool.isRequired,
    navigationAllowed: PropTypes.bool,
    // Controls
    setPlaying: PropTypes.func.isRequired,
    setPaused: PropTypes.func.isRequired,
    setPosition: PropTypes.func.isRequired,
    // Styles
    barColor: PropTypes.string,
    joyStickColor: PropTypes.string // Bar current position color
};
BottomControlsBar.defaultProps = {
    navigationAllowed: true
};
const styles = StyleSheet.create({
    barWrapper: {
        flexDirection: 'row',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        height: 70,
        paddingHorizontal: 20,
        justifyContent: 'space-between',
        alignItems: 'center'
    },
    currentTime: {
        color: 'white',
        width: 40
    },
    loadingBar: {
        flex: 1,
        marginHorizontal: 10
    },
    totalTime: {
        color: 'white',
        width: 40
    }
});
```
I think it's only a prop-type checking issue rather than a true bug itself. If you still get it, i'll pop a sample project in order to check that.

Best regards.
ScreamZ

**Comment by ScreamZ** [comment]
Seems to be related to the props as I said before, I published a patch.

Keep me in touch.

Best regards

**Comment by c-goettert** [comment]
First of all, thanks for the super-fast fix / reply!

Unfortunately, the warning still occures on the new version:
![bildschirmfoto 2018-04-24 um 10 41 46](https://user-images.githubusercontent.com/7591624/39176064-1f544208-47ac-11e8-9269-0a17ddd444ae.png)

As indicated in the warning, I am using a function as a prop (`const bottomControls = (props) => <MyControlsComponent {...props} />`). I think a quick fix would be to change the prop-type to `PropTypes.func`. I don't know if it's the cleanest solution. Maybe you could stick with `PropTypes.element`, but I think you need to adjust the render-function of the `VideoPlayer` then.

Thanks for the support!

**Comment by ScreamZ** [comment]
I thought that `element` was considering function component as element… seems not. 

I think we can use `PropTypes.oneOfType([PropTypes.element, PropTypes.func])`

Can you try it by hacking the node module and tell me if it fix ?

Regards

**Comment by c-goettert** [comment]
Yep, this will fix it!

**Comment by ScreamZ** [comment]
@c-goettert Released `alpha4`.

I close, thanks for reporting. :)

Regards
